version: '3.7'

configs:
  realm:
    file: ./realm.properties

services:
  rundeck:
    image: rundeck/rundeck:3.0.24
    links:
      - mysql
    environment:
      RUNDECK_SERVER_FORWARDED: "true"
      RUNDECK_DATABASE_DRIVER: com.mysql.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: rundeck
      RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
      NO_LOCAL_MYSQL: "true"
    volumes:
      - $${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
    configs:
      - source: realm
        target: /home/rundeck/server/config/realm.properties
    ports:
      - 80:4440
    networks:
      - rundeck
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=rundeck
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - rundeck

volumes:
  dbdata:

networks:
  rundeck: {}
